from __future__ import annotations

import math
from datetime import datetime, timezone
from typing import Any, Final

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import validates

from app.database.connection import Base


VERSION_30_MAXIMUM_CONFIDENCE_ADJUSTMENT: Final[float] = 4.0
VERSION_30_MINIMUM_COMPLETED_TRADES: Final[int] = 20
VERSION_30_MINIMUM_SIGNAL_CONFIDENCE: Final[float] = 80.0

MAXIMUM_SIGNAL_ID_LENGTH: Final[int] = 100
MAXIMUM_SYMBOL_LENGTH: Final[int] = 50
MAXIMUM_INTERVAL_LENGTH: Final[int] = 20
MAXIMUM_DIRECTION_LENGTH: Final[int] = 10
MAXIMUM_STATUS_LENGTH: Final[int] = 30
MAXIMUM_RESULT_LENGTH: Final[int] = 30
MAXIMUM_MARKET_SESSION_LENGTH: Final[int] = 20
MAXIMUM_MARKET_CONDITION_LENGTH: Final[int] = 80
MAXIMUM_ENGINE_VERSION_LENGTH: Final[int] = 100
MAXIMUM_TRADE_QUALITY_GRADE_LENGTH: Final[int] = 30
MAXIMUM_CONFIRMATIONS: Final[int] = 100

SUPPORTED_DIRECTIONS: Final[set[str]] = {
    "BUY",
    "SELL",
}

SUPPORTED_LEARNING_RESULTS: Final[set[str]] = {
    "WIN",
    "LOSS",
    "BREAKEVEN",
}


def _utc_datetime(
    value: datetime | None,
) -> datetime | None:
    if value is None:
        return None

    if not isinstance(
        value,
        datetime,
    ):
        raise ValueError(
            "Timestamp must be a datetime."
        )

    if value.tzinfo is None:
        return value.replace(
            tzinfo=timezone.utc
        )

    return value.astimezone(
        timezone.utc
    )


def _finite_float(
    value: Any,
    *,
    field_name: str,
    minimum: float | None = None,
    maximum: float | None = None,
    allow_none: bool = False,
) -> float | None:
    if value is None:
        if allow_none:
            return None

        raise ValueError(
            f"{field_name} is required."
        )

    if isinstance(
        value,
        bool,
    ):
        raise ValueError(
            f"{field_name} must be a valid number."
        )

    try:
        resolved = float(
            value
        )
    except (
        TypeError,
        ValueError,
        OverflowError,
    ) as exc:
        raise ValueError(
            f"{field_name} must be a valid number."
        ) from exc

    if not math.isfinite(
        resolved
    ):
        raise ValueError(
            f"{field_name} must be finite."
        )

    if (
        minimum is not None
        and resolved < minimum
    ):
        raise ValueError(
            f"{field_name} must be at least {minimum}."
        )

    if (
        maximum is not None
        and resolved > maximum
    ):
        raise ValueError(
            f"{field_name} must be at most {maximum}."
        )

    return resolved


def _strict_bool(
    value: Any,
    *,
    field_name: str,
    default: bool,
) -> bool:
    """Resolve one Boolean without arbitrary Python truthiness."""

    if value is None:
        return default

    if isinstance(
        value,
        bool,
    ):
        return value

    if isinstance(
        value,
        int,
    ) and value in {
        0,
        1,
    }:
        return bool(
            value
        )

    if isinstance(
        value,
        str,
    ):
        normalized = (
            value.strip()
            .lower()
        )

        if normalized in {
            "true",
            "1",
            "yes",
            "on",
        }:
            return True

        if normalized in {
            "false",
            "0",
            "no",
            "off",
        }:
            return False

    raise ValueError(
        f"{field_name} must be a boolean."
    )


def _bounded_text(
    value: Any,
    *,
    field_name: str,
    maximum_length: int,
    upper: bool = False,
    lower: bool = False,
    allow_none: bool = False,
) -> str | None:
    if value is None:
        if allow_none:
            return None

        raise ValueError(
            f"{field_name} is required."
        )

    resolved = str(
        value
    ).strip()

    if not resolved:
        if allow_none:
            return None

        raise ValueError(
            f"{field_name} is required."
        )

    if len(
        resolved
    ) > maximum_length:
        raise ValueError(
            f"{field_name} is too long."
        )

    if upper:
        resolved = resolved.upper()

    if lower:
        resolved = resolved.lower()

    return resolved


class TradeHistory(Base):
    """
    Store approved BUY and SELL signals generated by Blue-Trading-AI.

    Version 30 requirements:
    - Store market session and market condition.
    - Store completed-trade learning state.
    - Prevent confidence adjustments beyond +/-4.
    - Keep the platform analysis-only.

    WAIT, NO_TRADE, and blocked signals must not be saved as active trades.
    """

    __tablename__ = "trade_history"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    signal_id = Column(
        String(100),
        unique=True,
        index=True,
        nullable=False,
    )

    symbol = Column(
        String(50),
        index=True,
        nullable=False,
    )

    interval = Column(
        String(20),
        index=True,
        nullable=False,
    )

    direction = Column(
        String(10),
        index=True,
        nullable=False,
    )

    market_session = Column(
        String(20),
        index=True,
        nullable=True,
    )

    market_condition = Column(
        String(80),
        index=True,
        nullable=True,
    )

    entry_price = Column(
        Float,
        nullable=False,
    )

    stop_loss = Column(
        Float,
        nullable=False,
    )

    take_profit_1 = Column(
        Float,
        nullable=False,
    )

    take_profit_2 = Column(
        Float,
        nullable=False,
    )

    confidence = Column(
        Float,
        nullable=False,
    )

    directional_confidence = Column(
        Float,
        nullable=True,
    )

    confirmation_count = Column(
        Integer,
        default=0,
        nullable=False,
    )

    trade_quality_score = Column(
        Float,
        nullable=True,
    )

    trade_quality_grade = Column(
        String(30),
        nullable=True,
    )

    status = Column(
        String(30),
        default="ACTIVE",
        index=True,
        nullable=False,
    )

    result = Column(
        String(30),
        default="PENDING",
        index=True,
        nullable=False,
    )

    trade_allowed = Column(
        Boolean,
        default=True,
        nullable=False,
    )

    current_price = Column(
        Float,
        nullable=True,
    )

    exit_price = Column(
        Float,
        nullable=True,
    )

    tp1_hit = Column(
        Boolean,
        default=False,
        nullable=False,
    )

    tp2_hit = Column(
        Boolean,
        default=False,
        nullable=False,
    )

    stop_loss_hit = Column(
        Boolean,
        default=False,
        nullable=False,
    )

    profit_loss_points = Column(
        Float,
        default=0.0,
        nullable=False,
    )

    risk_reward_achieved = Column(
        Float,
        nullable=True,
    )

    trade_duration_seconds = Column(
        Integer,
        nullable=True,
    )

    learning_registered = Column(
        Boolean,
        default=False,
        index=True,
        nullable=False,
    )

    learning_registered_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    learning_result = Column(
        String(20),
        index=True,
        nullable=True,
    )

    learning_confidence_adjustment = Column(
        Float,
        default=0.0,
        nullable=False,
    )

    reason = Column(
        Text,
        nullable=True,
    )

    confirmation_details = Column(
        Text,
        nullable=True,
    )

    engine_version = Column(
        String(100),
        nullable=True,
    )

    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(
            timezone.utc
        ),
        index=True,
        nullable=False,
    )

    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(
            timezone.utc
        ),
        onupdate=lambda: datetime.now(
            timezone.utc
        ),
        nullable=False,
    )

    closed_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    @validates(
        "signal_id",
    )
    def validate_signal_id(
        self,
        key: str,
        value: Any,
    ) -> str:
        del key

        return str(
            _bounded_text(
                value,
                field_name="signal_id",
                maximum_length=MAXIMUM_SIGNAL_ID_LENGTH,
            )
        )

    @validates(
        "symbol",
    )
    def validate_symbol(
        self,
        key: str,
        value: Any,
    ) -> str:
        del key

        resolved = str(
            _bounded_text(
                value,
                field_name="symbol",
                maximum_length=MAXIMUM_SYMBOL_LENGTH,
                upper=True,
            )
        )

        allowed = set(
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-/"
        )

        if any(
            character not in allowed
            for character in resolved
        ):
            raise ValueError(
                "symbol contains unsupported characters."
            )

        return resolved

    @validates(
        "interval",
    )
    def validate_interval(
        self,
        key: str,
        value: Any,
    ) -> str:
        del key

        return str(
            _bounded_text(
                value,
                field_name="interval",
                maximum_length=MAXIMUM_INTERVAL_LENGTH,
                lower=True,
            )
        )

    @validates(
        "direction",
    )
    def validate_direction(
        self,
        key: str,
        value: Any,
    ) -> str:
        del key

        resolved = str(
            _bounded_text(
                value,
                field_name="direction",
                maximum_length=MAXIMUM_DIRECTION_LENGTH,
                upper=True,
            )
        )

        aliases = {
            "LONG": "BUY",
            "BULLISH": "BUY",
            "SHORT": "SELL",
            "BEARISH": "SELL",
        }

        resolved = aliases.get(
            resolved,
            resolved,
        )

        if resolved not in SUPPORTED_DIRECTIONS:
            raise ValueError(
                "direction must be BUY or SELL."
            )

        return resolved

    @validates(
        "market_session",
    )
    def validate_market_session(
        self,
        key: str,
        value: Any,
    ) -> str | None:
        del key

        resolved = _bounded_text(
            value,
            field_name="market_session",
            maximum_length=MAXIMUM_MARKET_SESSION_LENGTH,
            lower=True,
            allow_none=True,
        )

        if resolved is None:
            return None

        aliases = {
            "asia": "asian",
            "tokyo": "asian",
            "europe": "european",
            "london": "european",
            "usa": "us",
            "american": "us",
            "new_york": "us",
            "new york": "us",
            "ny": "us",
        }

        return aliases.get(
            resolved,
            resolved,
        )

    @validates(
        "market_condition",
    )
    def validate_market_condition(
        self,
        key: str,
        value: Any,
    ) -> str | None:
        del key

        resolved = _bounded_text(
            value,
            field_name="market_condition",
            maximum_length=MAXIMUM_MARKET_CONDITION_LENGTH,
            lower=True,
            allow_none=True,
        )

        if resolved is None:
            return None

        return resolved.replace(
            " ",
            "_",
        )

    @validates(
        "confidence",
    )
    def validate_confidence(
        self,
        key: str,
        value: Any,
    ) -> float:
        del key

        return float(
            _finite_float(
                value,
                field_name="confidence",
                minimum=0.0,
                maximum=100.0,
            )
        )

    @validates(
        "directional_confidence",
        "trade_quality_score",
    )
    def validate_optional_percentage(
        self,
        key: str,
        value: Any,
    ) -> float | None:
        return _finite_float(
            value,
            field_name=key,
            minimum=0.0,
            maximum=100.0,
            allow_none=True,
        )

    @validates(
        "entry_price",
        "stop_loss",
        "take_profit_1",
        "take_profit_2",
    )
    def validate_required_price(
        self,
        key: str,
        value: Any,
    ) -> float:
        return float(
            _finite_float(
                value,
                field_name=key,
                minimum=0.0,
            )
        )

    @validates(
        "current_price",
        "exit_price",
    )
    def validate_optional_price(
        self,
        key: str,
        value: Any,
    ) -> float | None:
        return _finite_float(
            value,
            field_name=key,
            minimum=0.0,
            allow_none=True,
        )

    @validates(
        "profit_loss_points",
        "risk_reward_achieved",
    )
    def validate_finite_performance(
        self,
        key: str,
        value: Any,
    ) -> float | None:
        return _finite_float(
            value,
            field_name=key,
            allow_none=(
                key == "risk_reward_achieved"
            ),
        )

    @validates(
        "confirmation_count",
    )
    def validate_confirmation_count(
        self,
        key: str,
        value: Any,
    ) -> int:
        del key

        if isinstance(
            value,
            bool,
        ):
            raise ValueError(
                "confirmation_count must be an integer."
            )

        try:
            resolved = int(
                value
            )
        except (
            TypeError,
            ValueError,
            OverflowError,
        ) as exc:
            raise ValueError(
                "confirmation_count must be an integer."
            ) from exc

        if not (
            0
            <= resolved
            <= MAXIMUM_CONFIRMATIONS
        ):
            raise ValueError(
                "confirmation_count is outside the supported range."
            )

        return resolved

    @validates(
        "trade_duration_seconds",
    )
    def validate_trade_duration(
        self,
        key: str,
        value: Any,
    ) -> int | None:
        del key

        if value is None:
            return None

        if isinstance(
            value,
            bool,
        ):
            raise ValueError(
                "trade_duration_seconds must be an integer."
            )

        try:
            resolved = int(
                value
            )
        except (
            TypeError,
            ValueError,
            OverflowError,
        ) as exc:
            raise ValueError(
                "trade_duration_seconds must be an integer."
            ) from exc

        return max(
            0,
            resolved,
        )

    @validates(
        "status",
        "result",
    )
    def validate_state_text(
        self,
        key: str,
        value: Any,
    ) -> str:
        maximum_length = (
            MAXIMUM_STATUS_LENGTH
            if key == "status"
            else MAXIMUM_RESULT_LENGTH
        )

        return str(
            _bounded_text(
                value,
                field_name=key,
                maximum_length=maximum_length,
                upper=True,
            )
        )

    @validates(
        "trade_quality_grade",
    )
    def validate_trade_quality_grade(
        self,
        key: str,
        value: Any,
    ) -> str | None:
        del key

        return _bounded_text(
            value,
            field_name="trade_quality_grade",
            maximum_length=MAXIMUM_TRADE_QUALITY_GRADE_LENGTH,
            allow_none=True,
        )

    @validates(
        "engine_version",
    )
    def validate_engine_version(
        self,
        key: str,
        value: Any,
    ) -> str | None:
        del key

        return _bounded_text(
            value,
            field_name="engine_version",
            maximum_length=MAXIMUM_ENGINE_VERSION_LENGTH,
            allow_none=True,
        )

    @validates(
        "trade_allowed",
        "tp1_hit",
        "tp2_hit",
        "stop_loss_hit",
        "learning_registered",
    )
    def validate_boolean_state(
        self,
        key: str,
        value: Any,
    ) -> bool:
        defaults = {
            "trade_allowed": True,
            "tp1_hit": False,
            "tp2_hit": False,
            "stop_loss_hit": False,
            "learning_registered": False,
        }

        return _strict_bool(
            value,
            field_name=key,
            default=defaults[key],
        )

    @validates(
        "learning_result",
    )
    def validate_learning_result(
        self,
        key: str,
        value: Any,
    ) -> str | None:
        del key

        if value is None:
            return None

        return self.normalise_learning_result(
            value
        )

    @validates(
        "learning_confidence_adjustment",
    )
    def validate_learning_confidence_adjustment(
        self,
        key: str,
        value: Any,
    ) -> float:
        del key

        return self.clamp_confidence_adjustment(
            value
        )

    @validates(
        "learning_registered_at",
        "created_at",
        "updated_at",
        "closed_at",
    )
    def validate_timestamps(
        self,
        key: str,
        value: datetime | None,
    ) -> datetime | None:
        resolved = _utc_datetime(
            value
        )

        if (
            key in {
                "created_at",
                "updated_at",
            }
            and resolved is None
        ):
            return datetime.now(
                timezone.utc
            )

        return resolved

    @staticmethod
    def normalise_learning_result(
        result: Any,
    ) -> str:
        """Convert a learning result into WIN, LOSS, or BREAKEVEN."""

        normalised = str(
            result or ""
        ).strip().upper()

        aliases = {
            "WON": "WIN",
            "PROFIT": "WIN",
            "TP1_HIT": "WIN",
            "TP2_HIT": "WIN",
            "LOST": "LOSS",
            "STOP_LOSS": "LOSS",
            "STOP_LOSS_HIT": "LOSS",
            "BREAK_EVEN": "BREAKEVEN",
            "BREAK-EVEN": "BREAKEVEN",
            "BE": "BREAKEVEN",
        }

        normalised = aliases.get(
            normalised,
            normalised,
        )

        if normalised not in SUPPORTED_LEARNING_RESULTS:
            raise ValueError(
                "Learning result must be WIN, LOSS, or BREAKEVEN."
            )

        return normalised

    @staticmethod
    def clamp_confidence_adjustment(
        confidence_adjustment: Any,
    ) -> float:
        """Clamp a learning adjustment to Version 30's +/-4 limit."""

        try:
            resolved_adjustment = float(
                confidence_adjustment
                if confidence_adjustment is not None
                else 0.0
            )
        except (
            TypeError,
            ValueError,
            OverflowError,
        ):
            resolved_adjustment = 0.0

        if not math.isfinite(
            resolved_adjustment
        ):
            resolved_adjustment = 0.0

        return max(
            -VERSION_30_MAXIMUM_CONFIDENCE_ADJUSTMENT,
            min(
                VERSION_30_MAXIMUM_CONFIDENCE_ADJUSTMENT,
                resolved_adjustment,
            ),
        )

    def mark_learning_registered(
        self,
        *,
        result: str,
        confidence_adjustment: float = 0.0,
        registered_at: datetime | None = None,
    ) -> None:
        """Mark the trade as processed by completed-trade learning."""

        resolved_time = _utc_datetime(
            registered_at
            or datetime.now(
                timezone.utc
            )
        )

        if resolved_time is None:
            resolved_time = datetime.now(
                timezone.utc
            )

        self.learning_registered = True
        self.learning_registered_at = resolved_time
        self.learning_result = (
            self.normalise_learning_result(
                result
            )
        )
        self.learning_confidence_adjustment = (
            self.clamp_confidence_adjustment(
                confidence_adjustment
            )
        )
        self.updated_at = resolved_time

    def clear_learning_registration(
        self,
    ) -> None:
        """Reset learning state for controlled repair or migration work."""

        resolved_time = datetime.now(
            timezone.utc
        )

        self.learning_registered = False
        self.learning_registered_at = None
        self.learning_result = None
        self.learning_confidence_adjustment = 0.0
        self.updated_at = resolved_time

    def validate_state(
        self,
    ) -> None:
        """Validate cross-field safety rules before persistence when invoked."""

        if self.direction not in SUPPORTED_DIRECTIONS:
            raise ValueError(
                "Only BUY and SELL trades are supported."
            )

        if (
            self.trade_allowed is True
            and self.status == "ACTIVE"
            and self.confidence
            < VERSION_30_MINIMUM_SIGNAL_CONFIDENCE
        ):
            raise ValueError(
                "Active trade confidence is below the Version 30 minimum."
            )

        if (
            self.learning_registered is True
            and self.learning_result
            not in SUPPORTED_LEARNING_RESULTS
        ):
            raise ValueError(
                "Registered learning state requires a valid learning result."
            )

        if (
            self.learning_registered is True
            and self.learning_registered_at is None
        ):
            raise ValueError(
                "Registered learning state requires learning_registered_at."
            )

        if (
            self.learning_registered is not True
            and (
                self.learning_registered_at is not None
                or self.learning_result is not None
            )
        ):
            raise ValueError(
                "Unregistered learning state cannot contain learning metadata."
            )

        if (
            self.closed_at is not None
            and self.created_at is not None
        ):
            created = _utc_datetime(
                self.created_at
            )
            closed = _utc_datetime(
                self.closed_at
            )

            if (
                created is not None
                and closed is not None
                and closed < created
            ):
                raise ValueError(
                    "closed_at cannot be earlier than created_at."
                )

    def __repr__(
        self,
    ) -> str:
        return (
            "<TradeHistory("
            f"signal_id='{self.signal_id}', "
            f"symbol='{self.symbol}', "
            f"direction='{self.direction}', "
            f"status='{self.status}', "
            f"result='{self.result}', "
            f"learning_registered={self.learning_registered}"
            ")>"
        )


__all__ = [
    "MAXIMUM_SIGNAL_ID_LENGTH",
    "SUPPORTED_DIRECTIONS",
    "SUPPORTED_LEARNING_RESULTS",
    "TradeHistory",
    "VERSION_30_MAXIMUM_CONFIDENCE_ADJUSTMENT",
    "VERSION_30_MINIMUM_COMPLETED_TRADES",
    "VERSION_30_MINIMUM_SIGNAL_CONFIDENCE",
]