"""describe change

Revision ID: 826026c92fcc
Revises: a0aef49a1c59
Create Date: 2026-08-02 22:58:56.245136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826026c92fcc'
down_revision: Union[str, Sequence[str], None] = 'a0aef49a1c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.alter_column('learning_registered',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('learning_confidence_adjustment',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.alter_column('learning_confidence_adjustment',
               existing_type=sa.FLOAT(),
               server_default=sa.text('(0.0)'),
               existing_nullable=False)
        batch_op.alter_column('learning_registered',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    # ### end Alembic commands ###
